from pydantic import BaseModel, Field
from typing import List

class LinterInput(BaseModel):
    file_path: str = Field(..., description="Path to the source file to lint")

    model_config = {"extra": "forbid"}

class LinterOutput(BaseModel):
    pylint_score: float = Field(..., description="Score generated by pylint (from 0.0 to 10.0)")
    mypy_errors: List[str] = Field(..., description="Type errors caught by mypy")
    issues: List[str] = Field(..., description="General linting feedback messages")

    model_config = {"extra": "forbid"}
